# Generated by Django 5.0.1 on 2024-05-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_store', '0002_alter_products_category_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/preview/shop/'),
        ),
    ]
