# Generated by Django 5.0.1 on 2024-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_store', '0004_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('love_moschino', 'Love Moschino'), ('hugo', 'HUGO'), ('calvin_klein', 'Calvin Klein'), ('nike', 'Nike'), ('adidas', 'Adidas'), ('vans', 'Vans'), ('converse', 'Converse'), ('new_balance', 'New Balance'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('asics', 'ASICS'), ('jordan_brand', 'Jordan Brand'), ('fila', 'Fila'), ('salomon', 'Salomon'), ('hoka_one_one', 'Hoka One One'), ('saucony', 'Saucony'), ('brooks', 'Brooks'), ('under_armour', 'Under Armour'), ('on_running', 'On Running'), ('mizuno', 'Mizuno'), ('skechers', 'Skechers'), ('merrell', 'Merrell'), ('timberland', 'Timberland'), ('palladium', 'Palladium'), ('superga', 'Superga'), ('veja', 'Veja'), ('allbirds', 'Allbirds'), ('apl', 'APL'), ('common_projects', 'Common Projects'), ('golden_goose', 'Golden Goose'), ('koio', 'Koio'), ('axel_arigato', 'Axel Arigato'), ('off_white', 'Off-White'), ('balenciaga', 'Balenciaga'), ('gucci', 'Gucci'), ('louis_vuitton', 'Louis Vuitton'), ('prada', 'Prada'), ('saint_laurent', 'Saint Laurent'), ('yeezy', 'Yeezy'), ('fear_of_god', 'Fear of God'), ('amiri', 'Amiri'), ('rick_owens', 'Rick Owens'), ('maison_margiela', 'Maison Margiela'), ('hermes', 'Hermès'), ('fendi', 'Fendi')], max_length=60),
        ),
    ]
